name: pipeline

on:
  push:
    branches:
      - 'main'
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.set_version.outputs.safe_version }}
    steps:
      -
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set application version
        id: set_version
        uses: kvendingoldo/semver-action@v1.8
        with:
          primary_branch: 'main'
      -
        name: Build and push
        run: |
          export TS=${{ steps.set_version.outputs.safe_version }}
          make build push version
      -
        name: Print image version
        run: echo ${{ steps.set_version.outputs.safe_version }}
